### ISSUE TITLE
ADF's not working outside of patched FS-UAE

### ISSUE THREAD

**Issue by jokker87** [cahirwpz/demoscene#111]
As to my experience, the resulting ADF only work in the patched FS-UAE, but not in any other emulator. Would be nice if the resulting ADF could be launched by any emulator.

Please correct me if i'm too dumb and talking s*** 👍

**Comment by cahirwpz** [comment]
Our framework is thightly coupled with `fs-uae` since we're actively using _trap-to-emulator_ feature. Moreover we're going to rely on this feature even more in the future. The feature has been sucessfully and extensively used by *TBL* in *Eon* demo as can be read in [The Tech Behind Eon: Tooling!](https://tbl.nu/2019/08/20/Tooling/) article.

ATM logging functionality [system/debug.h](https://github.com/cahirwpz/demoscene/blob/master/include/system/debug.h) uses _trap-to-emulator_ feature implemented by [uae.h](https://github.com/cahirwpz/demoscene/blob/master/include/uae.h). There's an easy way to disable logging and thus make executables run without `fs-uae`. This can be achieved removing `UAE` definition from compiler flags in [build/common.mk](https://github.com/cahirwpz/demoscene/blob/master/build/common.mk#L35).
